# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x04pose\"<\n\x0bPoseRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x19\n\x11new_skeleton_data\x18\x02 \x01(\x0c\",\n\x0cPoseResponse\x12\x1c\n\x14processed_image_data\x18\x01 \x01(\x0c\x32J\n\x13PoseChangingService\x12\x33\n\nChangePose\x12\x11.pose.PoseRequest\x1a\x12.pose.PoseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSEREQUEST']._serialized_start=20
  _globals['_POSEREQUEST']._serialized_end=80
  _globals['_POSERESPONSE']._serialized_start=82
  _globals['_POSERESPONSE']._serialized_end=126
  _globals['_POSECHANGINGSERVICE']._serialized_start=128
  _globals['_POSECHANGINGSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
