# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relighting.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'relighting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10relighting.proto\x12\nrelighting\"J\n\x0eRelightRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\tmask_data\x18\x02 \x01(\x0c\x12\x11\n\tjson_data\x18\x03 \x01(\x0c\"/\n\x0fRelightResponse\x12\x1c\n\x14processed_image_data\x18\x01 \x01(\x0c\x32W\n\x11RelightingService\x12\x42\n\x07Relight\x12\x1a.relighting.RelightRequest\x1a\x1b.relighting.RelightResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relighting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELIGHTREQUEST']._serialized_start=32
  _globals['_RELIGHTREQUEST']._serialized_end=106
  _globals['_RELIGHTRESPONSE']._serialized_start=108
  _globals['_RELIGHTRESPONSE']._serialized_end=155
  _globals['_RELIGHTINGSERVICE']._serialized_start=157
  _globals['_RELIGHTINGSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
