# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import relighting_pb2 as relighting__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in relighting_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelightingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Relight = channel.unary_unary(
                '/relighting.RelightingService/Relight',
                request_serializer=relighting__pb2.RelightRequest.SerializeToString,
                response_deserializer=relighting__pb2.RelightResponse.FromString,
                _registered_method=True)


class RelightingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Relight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelightingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Relight': grpc.unary_unary_rpc_method_handler(
                    servicer.Relight,
                    request_deserializer=relighting__pb2.RelightRequest.FromString,
                    response_serializer=relighting__pb2.RelightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relighting.RelightingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relighting.RelightingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelightingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Relight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relighting.RelightingService/Relight',
            relighting__pb2.RelightRequest.SerializeToString,
            relighting__pb2.RelightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
